CREATE TABLE `user` (
  `userid` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `usernn` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `userpwd` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `birth` int NOT NULL,
  `gender` tinyint(1) NOT NULL,
  `admin` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`userid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `movie` (
  `MOVIEIDX` int NOT NULL AUTO_INCREMENT,
  `TITLE` char(100) NOT NULL,
  `CONTENT` text,
  `POSTER` text,
  `GENRE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DIRECTOR` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ACTOR` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PLAYTIME` varchar(100) DEFAULT NULL,
  `AGE` char(1) DEFAULT NULL,
  `TRAILER` varchar(500) DEFAULT NULL,
  `WATCHOTT` varchar(100) DEFAULT NULL,
  `MAKER` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `OPENDT` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`MOVIEIDX`)
) ENGINE=InnoDB AUTO_INCREMENT=580 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `moviegrade` (
  `movieidx` int NOT NULL,
  `movielike` int DEFAULT NULL,
  `moviedislike` int DEFAULT NULL,
  PRIMARY KEY (`movieidx`),
  CONSTRAINT `moviegrade_FK` FOREIGN KEY (`movieidx`) REFERENCES `movie` (`MOVIEIDX`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `likedmovie` (
  `LIKEDIDX` int NOT NULL AUTO_INCREMENT,
  `MOVIEIDX` int NOT NULL,
  `LIKEDTIME` datetime NOT NULL,
  `USERID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `gender` tinyint DEFAULT NULL,
  `birth` int DEFAULT NULL,
  PRIMARY KEY (`LIKEDIDX`) USING BTREE
  KEY `likedmovie_FK` (`USERID`),
  CONSTRAINT `likedmovie_FK` FOREIGN KEY (`USERID`) REFERENCES `user` (`userid`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `board` (
  `BOARDIDX` int NOT NULL AUTO_INCREMENT,
  `USERID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CATEGORY` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `TITLE` varchar(200) NOT NULL,
  `DETAIL` varchar(15000) NOT NULL,
  `MOVIEIDX` int DEFAULT NULL,
  `LIKED` int DEFAULT '0',
  `POSTEDDATE` date DEFAULT NULL,
  `FILENAME` varchar(256) DEFAULT NULL,
  `FILESIZE` int DEFAULT '0',
  PRIMARY KEY (`BOARDIDX`),
  KEY `board_FK` (`USERID`),
  CONSTRAINT `board_FK` FOREIGN KEY (`USERID`) REFERENCES `user` (`userid`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `boardcomment` (
  `CIDX` int NOT NULL AUTO_INCREMENT,
  `BOARDIDX` int NOT NULL,
  `USERID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `DETAIL` varchar(2000) NOT NULL,
  `POSTEDDATE` date NOT NULL,
  PRIMARY KEY (`CIDX`),
  KEY `boardcomment_FK` (`BOARDIDX`),
  KEY `boardcomment_FK2` (`USERID`),
  CONSTRAINT `boardcomment_FK` FOREIGN KEY (`BOARDIDX`) REFERENCES `board` (`BOARDIDX`) ON DELETE CASCADE ON UPDATE RESTRICT
  CONSTRAINT `boardcomment_FK2` FOREIGN KEY (`USERID`) REFERENCES `user` (`userid`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `boardlike` (
  `LIKEIDX` int NOT NULL AUTO_INCREMENT,
  `BOARDIDX` int NOT NULL,
  `USERID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `LIKEDDATE` date NOT NULL,
  PRIMARY KEY (`LIKEIDX`),
  KEY `boardlike_FK` (`BOARDIDX`),
  KEY `boardlike_FK2` (`USERID`),
  CONSTRAINT `boardlike_FK` FOREIGN KEY (`BOARDIDX`) REFERENCES `board` (`BOARDIDX`) ON DELETE CASCADE
  CONSTRAINT `boardlike_FK2` FOREIGN KEY (`USERID`) REFERENCES `user` (`userid`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agora` (
  `AGORAIDX` int NOT NULL AUTO_INCREMENT,
  `USERID` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `MOVIEIDX` int NOT NULL,
  `AGORATITLE` varchar(20) NOT NULL,
  `AGORADETAIL` varchar(13000) NOT NULL,
  `POSTEDDATE` date NOT NULL,
  `FILENAME` varchar(256) DEFAULT NULL,
  `FILESIZE` int DEFAULT '0',
  KEY `agora_FK` (`USERID`),
  CONSTRAINT `agora_FK` FOREIGN KEY (`USERID`) REFERENCES `user` (`userid`) ON DELETE CASCADE
  PRIMARY KEY (`AGORAIDX`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agoradiscuss` (
  `DISCUSSIDX` int NOT NULL AUTO_INCREMENT,
  `AGORAIDX` int NOT NULL,
  `USERID` varchar(20) NOT NULL,
  `DETAIL` varchar(13000) NOT NULL,
  `POSTEDDATE` date NOT NULL,
  PRIMARY KEY (`DISCUSSIDX`),
  KEY `agoradiscuss_FK` (`AGORAIDX`),
  KEY `agoradiscuss_FK2` (`USERID`),
  CONSTRAINT `agoradiscuss_FK` FOREIGN KEY (`AGORAIDX`) REFERENCES `agora` (`AGORAIDX`) ON DELETE CASCADE
  CONSTRAINT `agoradiscuss_FK2` FOREIGN KEY (`USERID`) REFERENCES `user` (`userid`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `qnaboard` (
  `QNAIDX` int NOT NULL AUTO_INCREMENT,
  `USERID` varchar(20) NOT NULL,
  `TITLE` varchar(200) NOT NULL,
  `DETAIL` varchar(13000) NOT NULL,
  `POSTEDDATE` date NOT NULL,
  `ISSECRET` tinyint(1) NOT NULL DEFAULT '0',
  `FILENAME` varchar(256) DEFAULT NULL,
  `FILESIZE` int DEFAULT '0',
  PRIMARY KEY (`QNAIDX`)
  KEY `qna_FK` (`USERID`),
  CONSTRAINT `qna_FK` FOREIGN KEY (`USERID`) REFERENCES `user` (`userid`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `qnaanswer` (
  `ANSWERIDX` int NOT NULL AUTO_INCREMENT,
  `QNAIDX` int NOT NULL,
  `USERID` varchar(20) NOT NULL,
  `TITLE` varchar(200) NOT NULL,
  `DETAIL` varchar(13000) NOT NULL,
  `POSTEDDATE` date NOT NULL,
  `FILENAME` varchar(256) DEFAULT NULL,
  `FILESIZE` int DEFAULT '0',
  PRIMARY KEY (`ANSWERIDX`),
  KEY `qnaanswer_FK` (`QNAIDX`),
  KEY `qnaanswer_FK2` (`USERID`),
  CONSTRAINT `qnaanswer_FK` FOREIGN KEY (`QNAIDX`) REFERENCES `qnaboard` (`QNAIDX`) ON DELETE CASCADE
  CONSTRAINT `qnaanswer_FK2` FOREIGN KEY (`USERID`) REFERENCES `user` (`userid`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;